### ISSUE TITLE
Error on running the ./generate_csa_report.py results in the following:

### ISSUE THREAD

**Issue by samibegg-lw** [lacework/extensible-reporting#64]
2022-11-04 15:34:28 providers.lacework.host_vulns[10442] INFO Saving page 100
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3803, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5745, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5753, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'severity'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/samibegg/Downloads/extensible-reporting-main/./generate_csa_report.py", line 84, in <module>
    main()
  File "/Users/samibegg/Downloads/extensible-reporting-main/./generate_csa_report.py", line 81, in main
    report.generate_report(_shared(), report_save_path=report_save_path, use_cached_data=args.use_cached_data)
  File "/Users/samibegg/Downloads/extensible-reporting-main/reports/jinja2/csa_report.py", line 19, in generate_report
    host_vulns_data = gather_host_vulns_data(_shared, lw_provider)
  File "/Users/samibegg/Downloads/extensible-reporting-main/reports/jinja2/csa_report.py", line 54, in gather_host_vulns_data
    host_vulns_summary_by_host = _shared.t_lw.host_vulns_summary_by_host(host_vulns, limit=host_vulns_summary_by_host_limit)
  File "/Users/samibegg/Downloads/extensible-reporting-main/transformers/lacework/host_vulns_summary_by_host.py", line 9, in host_vulns_summary_by_host
    df = df[df['severity'].isin(severities)]
  File "/opt/homebrew/lib/python3.9/site-packages/pandas/core/frame.py", line 3804, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/opt/homebrew/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    raise KeyError(key) from err
KeyError: 'severity'

**Comment by jvogt** [comment]
Closed by #70
