### ISSUE TITLE
Running report results in error: ''NoneType' object has no attribute 'endswith''

### ISSUE THREAD

**Issue by mbonig** [lacework/extensible-reporting#75]
Tried running the report and got this:

```
./generate_csa_report_mac --author MattyB --customer Sandbox
[48942] WARNING: file already exists but should not: /var/folders/l5/nzdnfpfs4939qdd3bjm281xw0000gn/T/_MEI1Qd4sF/pyarrow/lib.cpython-38-darwin.so
Report will be saved to filename CSA_Report_Sandbox_11-21-22.html
2022-11-21 15:50:52 root[48961] INFO Loading report generator /var/folders/l5/nzdnfpfs4939qdd3bjm281xw0000gn/T/_MEI1Qd4sF/reports/jinja2/csa_report.py
2022-11-21 15:50:52 providers.lacework.host_vulns[48961] INFO Getting Host Vulns with following filters:
2022-11-21 15:50:52 providers.lacework.host_vulns[48961] INFO {'timeFilters': {'startTime': '2022-11-20T21:50:52+0000', 'endTime': '2022-11-21T22:50:52+0000'}}
Traceback (most recent call last):
  File "generate_csa_report.py", line 87, in <module>
  File "generate_csa_report.py", line 84, in main
  File "/var/folders/l5/nzdnfpfs4939qdd3bjm281xw0000gn/T/_MEI1Qd4sF/reports/jinja2/csa_report.py", line 19, in generate_report
    host_vulns_data = gather_host_vulns_data(_shared, lw_provider)
  File "/var/folders/l5/nzdnfpfs4939qdd3bjm281xw0000gn/T/_MEI1Qd4sF/reports/jinja2/csa_report.py", line 49, in gather_host_vulns_data
    host_vulns = lw_provider.host_vulns(_shared._25_hours_ago, _shared._now)
  File "providers/lacework/host_vulns.py", line 17, in host_vulns
  File "providers/lacework/__init__.py", line 13, in __call__
  File "laceworksdk/api/__init__.py", line 131, in __init__
  File "laceworksdk/http_session.py", line 58, in __init__
AttributeError: 'NoneType' object has no attribute 'endswith'
[48961] Failed to execute script 'generate_csa_report' due to unhandled exception!
```

**Comment by tmac1973** [comment]
This error occurs when you don't have any Lacework creds set up (such as a .lacework.toml file).
