### ISSUE TITLE
Report Generation Failing with [403] Forbidden - User not authorized

### ISSUE THREAD

**Issue by jbonner7** [lacework/extensible-reporting#78]
The report runs until it gets to the end and throws this error. My guess is this is not actually an auth error, but is being thrown because of the API threshold being reached:

2022-12-15 10:26:41 providers.lacework.host_vulns[95135] WARNING Lacework API returned maximum pages of host vuln results (100 pages). Processed dataset is likely incomplete.

2022-12-15 10:48:23 providers.lacework.container_vulns[95135] INFO Getting Container Vulnerabilities with following filters:
2022-12-15 10:48:23 providers.lacework.container_vulns[95135] INFO {'timeFilters': {'startTime': '2022-12-14T14:20:21+0000', 'endTime': '2022-12-15T15:20:21+0000'}, 'filters': [{'field': 'status', 'expression': 'eq', 'value': 'VULNERABLE'}, {'field': 'severity', 'expression': 'in', 'values': ['Critical', 'High']}]}
2022-12-15 10:48:23 laceworksdk.http_session[95135] INFO POST request to URI: https://customer.lacework.net/api/v2/Vulnerabilities/Containers/search
2022-12-15 10:48:26 providers.lacework.container_vulns[95135] INFO Saving page 1
2022-12-15 10:48:28 providers.lacework.integrations[95135] INFO Getting integrations
2022-12-15 10:48:28 laceworksdk.api.v1.integrations[95135] WARNING The 'get_all' function may be deprecated shortly, please consider switching to 'get'.
2022-12-15 10:48:28 laceworksdk.api.v1.integrations[95135] INFO Getting cloud integrations from Lacework...
2022-12-15 10:48:28 laceworksdk.http_session[95135] INFO GET request to URI: https://customer.lacework.net/api/v1/external/integrations
2022-12-15 10:48:28 laceworksdk.http_session[95135] WARNING Lacework's v1 APIs are scheduled to be deprecated and will not allow usage of after December 2022.
Traceback (most recent call last):
  File "/Users/sorcerersupreme/Documents/csa_reports/extensible-reporting-main/./generate_csa_report.py", line 87, in <module>
    main()
  File "/Users/sorcerersupreme/Documents/csa_reports/extensible-reporting-main/./generate_csa_report.py", line 84, in main
    report.generate_report(_shared(), report_save_path=report_save_path, use_cached_data=args.use_cached_data)
  File "/Users/sorcerersupreme/Documents/csa_reports/extensible-reporting-main/reports/jinja2/csa_report.py", line 21, in generate_report
    compliance_data = gather_compliance_data(_shared, lw_provider)
  File "/Users/sorcerersupreme/Documents/csa_reports/extensible-reporting-main/reports/jinja2/csa_report.py", line 110, in gather_compliance_data
    integrations = lw_provider.integrations()
  File "/Users/sorcerersupreme/Documents/csa_reports/extensible-reporting-main/providers/lacework/integrations.py", line 8, in integrations
    integrations = lw().integrations.get_all()['data']
  File "/usr/local/lib/python3.9/site-packages/laceworksdk/api/v1/integrations.py", line 101, in get_all
    return self.get()
  File "/usr/local/lib/python3.9/site-packages/laceworksdk/api/v1/integrations.py", line 88, in get
    response = self._session.get(api_uri)
  File "/usr/local/lib/python3.9/site-packages/laceworksdk/http_session.py", line 297, in get
    response = self._request("GET", uri, params=params, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/laceworksdk/http_session.py", line 256, in _request
    self._check_response_code(response, DEFAULT_SUCCESS_RESPONSE_CODES)
  File "/usr/local/lib/python3.9/site-packages/laceworksdk/http_session.py", line 123, in _check_response_code
    raise ApiError(response)
laceworksdk.exceptions.ApiError: [403] Forbidden - User not authorized.

**Comment by jvogt** [comment]
This is resolved with the latest version v0.10.0
