### ISSUE TITLE
Running report from GUI results in ninja error

### ISSUE THREAD

**Issue by dglauche** [lacework/extensible-reporting#88]
```
      File "modules\gui_main.py", line 189, in run_report
        self.report = self.report_generator.generate(self.window.lineEditCustomer.text,
      File "C:\Users\XXXXX\AppData\Local\Temp\_MEI425642\modules\reports\reportgen_csa_detailed.py", line 79, in generate
        return self.render(customer, author, pagesize=pagesize)
      File "C:\Users\XXXXX\AppData\Local\Temp\_MEI425642\modules\reports\reportgen_csa_detailed.py", line 48, in render
        return self.template.render(
      File "jinja2\environment.py", line 1301, in render
      File "jinja2\environment.py", line 936, in handle_exception
      File "C:\Users\XXXXX\AppData\Local\Temp\_MEI425642\templates\csa_detailed_report.jinja2", line 650, in top-level template code
        {% if not host_vulns_data.fixable_vulns.empty %}
      File "jinja2\environment.py", line 485, in getattr
    jinja2.exceptions.UndefinedError: 'bool object' has no attribute 'fixable_vulns'

Traceback (most recent call last):
  File "modules\gui_main.py", line 189, in run_report
  File "C:\Users\XXXXX\AppData\Local\Temp\_MEI425642\modules\reports\reportgen_csa_detailed.py", line 79, in generate
    return self.render(customer, author, pagesize=pagesize)
  File "C:\Users\XXXXX\AppData\Local\Temp\_MEI425642\modules\reports\reportgen_csa_detailed.py", line 48, in render
    return self.template.render(
  File "jinja2\environment.py", line 1301, in render
  File "jinja2\environment.py", line 936, in handle_exception
  File "C:\Users\XXXXX\AppData\Local\Temp\_MEI425642\templates\csa_detailed_report.jinja2", line 650, in top-level template code
    {% if not host_vulns_data.fixable_vulns.empty %}
  File "jinja2\environment.py", line 485, in getattr
jinja2.exceptions.UndefinedError: 'bool object' has no attribute 'fixable_vulns'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "modules\gui_main.py", line 203, in run_report
TypeError: descriptor 'showMessage' for 'PySide6.QtWidgets.QErrorMessage' objects doesn't apply to a 'str' object
```

**Comment by dglauche** [comment]
Seems like the issue is related to the Detailed Cloud Security Assessment
